# Generated by Django 3.2.3 on 2026-05-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_vaccine_catvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='catvaccination',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=500)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cats.cat')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='cats.catvaccination')),
            ],
        ),
    ]
